version: '0.3'

services:
  node-1:
    image: tagfs
    container_name: node-1
    command: /bin/sh -c "echo 'export IP=10.0.0.2' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.2
    expose:
      - 9090
  
  node-2:
    image: tagfs
    container_name: node-2
    command: /bin/sh -c "echo 'export IP=10.0.0.3' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.3
    expose:
      - 9090
  
  node-3:
    image: tagfs
    container_name: node-3
    command: /bin/sh -c "echo 'export IP=10.0.0.4' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.4
    expose:
      - 9090
  
  node-4:
    image: tagfs
    container_name: node-4
    command: /bin/sh -c "echo 'export IP=10.0.0.5' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.5
    expose:
      - 9090
  
  node-5:
    image: tagfs
    container_name: node-5
    command: /bin/sh -c "echo 'export IP=10.0.0.6' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.6
    expose:
      - 9090
  
  node-6:
    image: tagfs
    container_name: node-6
    command: /bin/sh -c "echo 'export IP=10.0.0.7' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.7
    expose:
      - 9090
  
  node-7:
    image: tagfs
    container_name: node-7
    command: /bin/sh -c "echo 'export IP=10.0.0.8' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.8
    expose:
      - 9090
  
  node-8:
    image: tagfs
    container_name: node-8
    command: /bin/sh -c "echo 'export IP=10.0.0.9' >> ~/.bashrc && while sleep 1000; do :; done"
    networks:
      default:
        ipv4_address: 10.0.0.9
    expose:
      - 9090

networks:
  default:
    external: true
    name: tagfs-net